### ISSUE TITLE
Changes to MaxMind database downloads

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel-iplookup#3]
MaxMind notified account owners (like me) that they are changing how database downloads work. I'm not sure exactly if or when the method used by this plugin will stop working, but it seems likely that changes will be required.

The documentation on downloading databases automatically is here: https://dev.maxmind.com/geoip/updating-databases

Relevant section:

> In order to download the databases from a script or program, please use the permalinks found on the [GeoIP download page](https://www.maxmind.com/en/accounts/current/geoip/downloads). Please note that you will be redirected from these permalinks because MaxMind uses R2 presigned URLs for database downloads. You should make sure that your HTTP client follows redirects and there are no proxy or firewall settings that would block requests to the host we are redirecting to. We will redirect requests using HTTPS on the following hostname:
>
> > mm-prod-geoip-databases.a2649acb697e2c09b632799562c076f2.r2.cloudflarestorage.com
>
> To directly download databases, follow these steps:
>
> - In the “Download Links” column, click “Get Permalink(s)” for the desired database.
> - Copy the permalink(s) provided in the modal window.
> - Provide your [account ID](https://support.maxmind.com/hc/en-us/articles/4412951066779-Find-my-Account-ID) and [your license key](https://www.maxmind.com/en/accounts/current/license-key) using [Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) to authenticate.
> - If you are using wget or curl from a shell script, please be sure to quote the URL.
>
> This download will return a compressed file in gzip (for binary) or zip (for CSV) format, which can be uncompressed using a program like [7-Zip](https://www.7-zip.org/) or [gzip](https://www.gzip.org/).

The example cURL command given uses a different URL format than this plugin:

```
curl -O -J -L -u YOUR_ACCOUNT_ID:YOUR_LICENSE_KEY 'https://download.maxmind.com/geoip/databases/GeoIP2-City-CSV/download?suffix=zip'
```

vs. the current URL built from `https://download.maxmind.com/app/geoip_download` as the base + parameters as below:

- `license_key`
- `suffix`
- `edition_id`

The final URL ends up being something like `https://download.maxmind.com/app/geoip_download?license_key=asdf1234&suffix=tar.gz&edition_id=GeoLite2-ASN` — which, again, could stop working as early as next month.

**Comment by dgw** [comment]
An alternative suggested in our IRC: [this repo](https://github.com/P3TERX/GeoLite.mmdb/tree/download) that automatically downloads and publishes the files. Now that really _would_ let us quit shipping a license key in the source code, _and_ obviate any need to build out the configuration/documentation for users to provide their own.

**Comment by christophermluna** [comment]
hey there! i'm christopher luna, a product manager at MaxMind handling GeoIP issues. i just wanted to reach out to let you know that the download method you're currently using with base + parameters should continue to work. you don't need to change the method of download to match the `curl` example, you just need to ensure that your downloading client is configured to accept redirects and that the downloading host doesn't have firewall settings that will block connections to the new hostname.

**Comment by dgw** [comment]
No changes needed to MaxMind download code, confirmed by testing, and by a PM commenting above (thanks!).
